Repository motoon-eg/dokan-store, pull requests merged in 2022-07, with the labels that each got.

#24 build: Update Swiftlint Configurations 〽️
  .swiftlint.yml
  Dokan/Dokan.xcodeproj/project.pbxproj
  Dokan/Dokan/.swiftlint.yml
  Dokan/Dokan/AppDelegate.swift
  Dokan/Dokan/SceneDelegate.swift
  Dokan/Dokan/ViewController.swift
Labels: help wanted

#32 Feat/add Custom Xcode MVVM Template
  Template/MVVM Files Generator.xctemplate/TemplateIcon.png
  Template/MVVM Files Generator.xctemplate/TemplateIcon@2x.png
  Template/MVVM Files Generator.xctemplate/TemplateInfo.plist
  Template/MVVM Files Generator.xctemplate/WithXIB/___FILEBASENAME___ViewController.swift
  Template/MVVM Files Generator.xctemplate/WithXIB/___FILEBASENAME___ViewController.xib
  Template/MVVM Files Generator.xctemplate/WithXIB/___FILEBASENAME___ViewModel.swift
  Template/MVVM Files Generator.xctemplate/WithXIB/___FILEBASENAME___ViewModelType.swift
  Template/MVVM Files Generator.xctemplate/WithoutXIB/___FILEBASENAME___ViewController.swift
  Template/MVVM Files Generator.xctemplate/WithoutXIB/___FILEBASENAME___ViewModel.swift
  Template/MVVM Files Generator.xctemplate/WithoutXIB/___FILEBASENAME___ViewModelType.swift
  Template/README.md
Labels: enhancement, help wanted

#34 feat: add core layer
  Core/Package.swift
  Core/README.md
  Core/Sources/Core/Core.swift
  Core/Tests/CoreTests/CoreTests.swift
  Dokan.xcworkspace/contents.xcworkspacedata
  Dokan/Dokan.xcodeproj/project.pbxproj
Labels: help wanted

#48 feat/ Create Login View Controller 🎃
  Dokan/Dokan.xcodeproj/project.pbxproj
  Dokan/Dokan/Scenes/Login/LoginViewController.swift
  Dokan/Dokan/Scenes/Login/LoginViewController.xib
  Dokan/Dokan/Scenes/Login/LoginViewModel.swift
  Dokan/Dokan/Scenes/Login/LoginViewModelType.swift
  Dokan/DokanTests/Scenes/Login/LoginViewControllerTests.swift
  Dokan/DokanTests/Scenes/Login/LoginViewModelTests.swift
Labels: enhancement, help wanted

#47 Adding custom font and colors assists 🎨
  Dokan/Dokan/Fonts/DMSans-Bold.ttf
  Dokan/Dokan/Fonts/DMSans-Medium.ttf
  Dokan/Dokan/Fonts/DMSans-Regular.ttf
  Dokan/Dokan/Info.plist
Labels: ready for review

#57 feat: Adding DMSans Fonts 🥇
  Dokan/Dokan/ViewController.swift
  UIDokan/Sources/UIDokan/Extentions/Font+Style.swift
Labels: ready for review

#75 feat: Add navigation bar style to product details 🎃
  Dokan/Dokan.xcodeproj/project.pbxproj
  Dokan/Dokan/Assets.xcassets/bell-badge.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/bell-badge.imageset/bell.png
  Dokan/Dokan/Assets.xcassets/bell.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/bell.imageset/bell.png
  Dokan/Dokan/Assets.xcassets/redo.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/redo.imageset/redo.png
  Dokan/Dokan/Assets.xcassets/search.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/search.imageset/search.png
  Dokan/Dokan/Assets.xcassets/shopping-cart-badge.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/shopping-cart-badge.imageset/shopping-cart.png
  Dokan/Dokan/Assets.xcassets/shopping-cart.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/shopping-cart.imageset/shopping-cart.png
  Dokan/Dokan/Assets.xcassets/star.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/star.imageset/star.png
  Dokan/Dokan/Scenes/ProductDetails/ProductDetailsViewController.swift
  Dokan/Dokan/Scenes/ProductDetails/Views/ProductDetailsNavigationBarBehavior.swift
Labels: ready for review

#71 feat: Ceate description text view with "read more" option
  Dokan/Dokan/Scenes/ProductDetails/ProductDetailsViewController.swift
  Dokan/Dokan/Scenes/ProductDetails/ProductDetailsViewController.xib
  Dokan/Dokan/Scenes/ProductDetails/Views/ProductDetailsNavigationBarBehavior.swift
  Dokan/Dokan/Scenes/Verification/VerificationViewController.xib
  UIDokan/Sources/UIDokan/ReusableViews/ReadMoreTextView.swift
Labels: ready for review
