Repository motoon-eg/dokan-store, pull requests merged in 2022-08, with the labels that each got.

#66 feat: Add seller info view to product details 🍿
  Dokan/Dokan.xcodeproj/project.pbxproj
  Dokan/Dokan/Assets.xcassets/vector.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/vector.imageset/vector.png
  Dokan/Dokan/Assets.xcassets/verified.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/verified.imageset/Shield Done.png
  Dokan/Dokan/Scenes/ProductDetails/ProductDetailsViewController.swift
  Dokan/Dokan/Scenes/ProductDetails/ProductDetailsViewController.xib
  Dokan/Dokan/Scenes/ProductDetails/Views/InfoSellerView/InfoSellerView.swift
  Dokan/Dokan/Scenes/ProductDetails/Views/InfoSellerView/InfoSellerView.xib
  Dokan/Dokan/Scenes/ProductDetails/Views/InfoSellerView/InfoSellerViewDelegate.swift
  UIDokan/Sources/UIDokan/Extensions/UILabel+Extension.swift
Labels: ready for review

#89 fix/develop-confilct-issue 🥹
  Dokan/Dokan.xcodeproj/project.pbxproj
Labels: help wanted, ready for review

#54 feat: UIButton, UILabel and UITextField Design Components 🖌
  Dokan/Dokan/Assets.xcassets/star.imageset/Contents.json
  Dokan/Dokan/Assets.xcassets/star.imageset/star.png
  Dokan/DokanTests/Scenes/Registratio9nTest/RegisterViewControllerTests.swift
  UIDokan/Sources/UIDokan/Extentions/UITextField+EyeToggle.swift
  UIDokan/Sources/UIDokan/ReusableViews/StackViews/LabelAndTextField/LabelAndTextfield.swift
  UIDokan/Sources/UIDokan/ReusableViews/StackViews/LabelAndTextField/LabelAndTextfield.xib
  UIDokan/Sources/UIDokan/ReusableViews/StackViews/TitleAndBodyLabels/TitleAndBodyLabels.swift
  UIDokan/Sources/UIDokan/ReusableViews/StackViews/TitleAndBodyLabels/TitleAndBodyLabels.xib
  UIDokan/Sources/UIDokan/Style/UIButton+Style.swift
  UIDokan/Sources/UIDokan/Style/UILabel+Style.swift
  UIDokan/Sources/UIDokan/Style/UITextField+Style.swift
Labels: work in progress

#5 feat: Add abstract networking layer based on Alamofire 🔥
  Networking/Sources/Networking/Models/Product.swift
  Networking/Sources/Networking/Models/RemoteError.swift
  Networking/Sources/Networking/Network/AlamofireNetwork.swift
  Networking/Sources/Networking/Network/Network.swift
  Networking/Sources/Networking/Networking.swift
  Networking/Sources/Networking/Remote/ProductsRemote.swift
  Networking/Sources/Networking/Remote/Remote.swift
  Networking/Sources/Networking/Requests/FakeStoreRequest.swift
  Networking/Sources/Networking/Settings.swift
  Networking/Sources/Networking/Validators/RemoteValidator.swift
Labels: proposal

#108 doc: Create Clean Architecture Layers with Implementation
  Core/Package.swift
  Core/Sources/Core/Models/DomainConvertible/Product.swift
  Core/Sources/Core/Repository/ProductRepository.swift
  Core/Sources/Core/Tools/DomainConvertible.swift
  Core/Sources/Core/Tools/RepositoryProvider.swift
  Dokan/Dokan.xcodeproj/project.pbxproj
  Dokan/Dokan/ServiceLocator/ServiceLocator.swift
  Domain/Sources/Domain/Model/Product.swift
  Domain/Sources/Domain/Provider/RepositoryProvider.swift
  Domain/Sources/Domain/Repository/ProductRepository.swift
  Domain/Sources/Domain/Repository/UserRepository.swift
  Networking/Sources/Networking/Models/Product.swift
  Networking/Sources/Networking/Remote/ProductsRemote.swift
Labels: documentation, proposal
